package ag.sportradar.mobile.player.data.sdk.loging

/**
 * Defines a contract for logging operations within the Player SDK.
 *
 * Implementations of this interface are responsible for handling log messages
 * generated by the player components, allowing for customization of log output
 * destinations (e.g., console, file, remote server) and filtering based on severity.
 */
interface PlayerLoggingProvider {

    /**
     * Logs an error message.
     *
     * @param message The message to be logged.
     * @param tag The tag to use for the log entry. Defaults to "SRAVPlayer".
     * @param throwable An optional [Throwable] to log associated with the error.
     */
    fun error(message: String, tag: String = TAG, throwable: Throwable? = null)

    /**
     * Logs a warning message.
     *
     * @param message The message you would like logged.
     * @param tag Used to identify the source of a log message. It usually identifies the class or activity where the log call occurs. Defaults to "SRAVPlayer".
     * @param throwable An exception to log (optional).
     */
    fun warning(message: String, tag: String = TAG, throwable: Throwable? = null)

    /**
     * Logs an informational message.
     *
     * Use this method to log standard operational events that highlight the progress of the application
     * or the player SDK. These messages are generally useful for understanding the flow of execution
     * but do not indicate an error or potential problem.
     *
     * @param message The message text to be logged.
     * @param tag An optional tag to identify the source of the log message. Defaults to "SRAVPlayer".
     * @param throwable An optional [Throwable] associated with the log message, if applicable.
     */
    fun info(message: String, tag: String = TAG, throwable: Throwable? = null)

    /**
     * Logs a debug message.
     *
     * Use this level for detailed information that is typically only useful for debugging and development.
     * These logs are usually disabled in production builds to reduce noise and performance overhead.
     *
     * @param message The message to be logged.
     * @param tag The tag identifying the source of the log message. Defaults to "SRAVPlayer".
     * @param throwable An optional [Throwable] associated with the message.
     */
    fun debug(message: String, tag: String = TAG, throwable: Throwable? = null)

    /**
     * Logs a verbose message.
     *
     * Use this level for the most detailed logging information, typically used for diagnosing complex issues.
     * These logs are extremely chatty and are usually only enabled during deep troubleshooting.
     *
     * @param message The detailed message to be logged.
     * @param tag The tag identifying the source of the log message. Defaults to "SRAVPlayer".
     * @param throwable An optional [Throwable] associated with the message.
     */
    fun verbose(message: String, tag: String = TAG, throwable: Throwable? = null)

    companion object {
        const val TAG = "SRAVPlayer"
    }
}